### ISSUE TITLE
Use valarray instead of vector in monomial_mul in monomials.cpp

### ISSUE THREAD

**Issue by certik** [sympy/symengine#111]
Citing from [1]:

> The `vector` described in §4.4.1 was designed to be a general
mechanism for holding values, to be flexible, and to fit into the
architecture of containers, iterators, and algorithms. However, it does
not support mathematical vector operations. Adding such operations
to `vector` would be easy, but its generality and flexibility precludes
optimizations that are often considered essential for serious numerical
work. Consequently, the standard library provides (in `<valarray>`) a
`vector`-like template, called `valarray`, that is less general and more
amenable to optimization for numerical computation

> The usual arithmetic operations and the most common mathematical
functions are supported for `valarray`s.

[1] Stroustrup, B. (2013). The C++ Programming Language (4th ed., p. 1368). Addison-Wesley Professional.

**Comment by shivamvats** [comment]
@certik Currently, monomial_mul, poly_mul etc have vector parameters. Since poly_mul depends on monomial_mul, we can't change monomial_mul in isolation. Do you want to completely replace vec_int with valarray or do you want to use valarray for computation only (via conversions)?

**Comment by certik** [comment]
I think it needs to be replaced everywhere. And benchmarked.

**Comment by Sumith1896** [comment]
@certik @shivamvats This was tried out, but `valarray` really slowed down the benchmarks.
`valarray` slows down stuff in the current way monomial is handled, doesn't look promising but still a structure to be kept in mind.
Do you want this issue open?

**Comment by certik** [comment]
Thanks @Sumith1896 for trying it out. I think we can close it now.

**Comment by Sumith1896** [comment]
Cheers
