### ISSUE TITLE
Use testing framework

### ISSUE THREAD

**Issue by certik** [sympy/symengine#282]
Currently we don't use any testing framework, we simply just execute the tests and return exit code 0 or 1. And that works. But sometimes it would be nice to have more features, i.e. better test reporting, and so on. We might use this one:

https://github.com/philsquared/Catch

it looks simple and powerful.

**Comment by certik** [comment]
Another option is to use Google Test: https://code.google.com/p/googletest/

**Comment by certik** [comment]
We should use Catch.

**Comment by Sumith1896** [comment]
+1

**Comment by abinashmeher999** [comment]
+1

**Comment by Sumith1896** [comment]
@certik There are two styles in which tests are written under `Catch` (if I am getting this right)
1. `TEST_CASE()` followed by `SECTION`
2. `SCENARIO()` with `WHEN` - `THEN` states
What should we follow?

**Comment by certik** [comment]
As a first step, I would just use `TEST_CASE()` and `REQUIRE` instead of all our asserts, no sections. That directly maps to what we have there. Then once this is in and everything works, we can improve the test suite to use the 2. option.

**Comment by Sumith1896** [comment]
Yes and make sure that test written then onwards are clean.

**Comment by certik** [comment]
Right.

**Comment by Sumith1896** [comment]
Also, I plan to use `REQUIRE` instead of `CHECK` difference being the former stops at first failure. 
What do you think?

**Comment by certik** [comment]
Yes, I would use REQUIRE. For new tests that we write in the future, we can use both, but for now I would convert each assert into REQUIRE.

**Comment by Sumith1896** [comment]
Made SymEngine use Catch(https://github.com/sympy/symengine/pull/484)

**Comment by isuruf** [comment]
Closed via #493
