### ISSUE TITLE
Enable Travis tests for clang on OS X

### ISSUE THREAD

**Issue by sushant-hiray** [sympy/symengine#347]
To make sure code is compatible with OS X too.
Travis supports multiple OS and multiple compilers.

**Comment by isuruf** [comment]
@sushant-hiray Did we get support for multiple OS?

**Comment by sushant-hiray** [comment]
@isuruf Here is the final response from Travis

*Me*: Would it possible to turn on if we only wish to test some tests.
Basically test only clang and gcc-4.8 specifics on OS X and defer the python tests till the support is added?

*Travis*: That is a bit difficult, unfortunately. You can switch to "language: c" and run your tests, but then you will have to manage your own Python runtimes, since virtualenv is not set up for that VM.
You can try switching and tinkering first, and when you have your build environment set up, we can revisit this.

Since #354  has been merged, I'll re-request for multiple OS support now.

**Comment by isuruf** [comment]
Thanks

**Comment by sushant-hiray** [comment]
Update: Currently Travis has reached its max capacity on Mac workers, so we cannot get the access immediately. We can ask for the access again after a month or so.

**Comment by isuruf** [comment]
Closed via #473
