### ISSUE TITLE
Figure out how to use Teuchos::RCP in Debug mode

### ISSUE THREAD

**Issue by certik** [sympy/symengine#450]
The `Teuchos::RCP` provides 100% safety in Debug mode (our own `RCP` implementation is not 100% safe in Debug mode --- it can't find dangling pointers). However, we currently use a self reference idiom in SymEngine:
```c++
RCP<const Log> self = rcp_const_cast<Log>(rcp(this));
```
We should create a function or a macro, that returns `RCP<const X> self` for a class `X`. The reason is that this idiom is the only place, where `Teuchos::RCP` would not work as a drop in replacement (since Teuchos does not store the refcount in our class). However, there is a way to use `Teuchos::RCP` for this idiom too, one has to add some member variables into the class, perhaps a weak `RCP` pointer to itself, or something like that. This would be done in Debug mode only. In Release mode, we will continue using our own fast implementation.

**Comment by isuruf** [comment]
Fixed via #499
