### ISSUE TITLE
Allow to optionally link with tcmalloc

### ISSUE THREAD

**Issue by certik** [sympy/symengine#452]
I tested [jemalloc](http://www.canonware.com/jemalloc/) and [tcmalloc](https://code.google.com/p/gperftools/). Compared to the default malloc, the `jemalloc` actually slowed things down for the `expand2` benchmark (it looks like it is good for more than 1 thread, but just for 1 thread it seems slower, unless I did something wrong). However, `tcmalloc` is significantly faster (even for 1 thread, which is what we do). One can try it out easily as follows:
```
certik@redhawk:~/repos/symengine/benchmarks(master)$ ./expand2
Expanding: (w + (w + x + y + z)**15)*(w + x + y + z)**15
821ms
number of terms: 6272
certik@redhawk:~/repos/symengine/benchmarks(master)$ LD_PRELOAD=/home/certik/repos/hashstack/d2/lib/libtcmalloc.so ./expand2
Expanding: (w + (w + x + y + z)**15)*(w + x + y + z)**15
690ms
number of terms: 6272
```
I took the best timings out of about 15 tries or so. That's a solid 16% speedup.

One consistently finds similar results across the board, e.g.:
```
certik@redhawk:~/repos/symengine/benchmarks(master)$ ./expand1
Expanding: (w + x + y + z)**60
108ms
number of terms: 39711
certik@redhawk:~/repos/symengine/benchmarks(master)$ LD_PRELOAD=/home/certik/repos/hashstack/d2/lib/libtcmalloc.so ./expand1
Expanding: (w + x + y + z)**60
67ms
number of terms: 39711
```
That's 38% speedup. More results:
```
certik@redhawk:~/repos/symengine/benchmarks(master)$ ./expand3
Expanding: (x**y + y**x + z**x)**100
18ms
number of terms: 5151
certik@redhawk:~/repos/symengine/benchmarks(master)$ LD_PRELOAD=/home/certik/repos/hashstack/d2/lib/libtcmalloc.so ./expand3
Expanding: (x**y + y**x + z**x)**100
15ms
number of terms: 5151

certik@redhawk:~/repos/symengine/benchmarks(master)$ ./eval_double1 
4386ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15
certik@redhawk:~/repos/symengine/benchmarks(master)$ LD_PRELOAD=/home/certik/repos/hashstack/d2/lib/libtcmalloc.so ./eval_double1
3761ms
r (double) = 9.85647
r (exact)  = 9.85647
error      = 5.32907e-15

certik@redhawk:~/repos/symengine/benchmarks(master)$ ./matrix_mul1
Multiplying Two Matrices; matrix dimensions: 4 x 4
37 microseconds
certik@redhawk:~/repos/symengine/benchmarks(master)$ LD_PRELOAD=/home/certik/repos/hashstack/d2/lib/libtcmalloc.so ./matrix_mul1
Multiplying Two Matrices; matrix dimensions: 4 x 4
29 microseconds
```

The `LD_PRELOAD` is just a quick hack to try things out, the way to use it is to link SymEngine against it. That is, allow the user to optionally specify `-DWITH_TCMALLOC=yes` and cmake would link against it directly. That way SymEngine links to `tcmalloc` like to any other library, and users can optionally install it to get faster results.

**Comment by isuruf** [comment]
+1. 
I ran the benchmarks for a few times and got the lowest timings

Benchmark | with `tcmalloc` | without
----------------|---------------------|----------
expand2 | 887ms | 1091ms
expand1 | 83ms | 86ms
eval_double1 | 4796ms | 6681ms
matrix_mul1 | 38ms | 43ms
expand3 | 16ms | 18ms

**Comment by certik** [comment]
Thanks for verifying it on your computer. We should use this when installing into Sage.
