### ISSUE TITLE
Add DNDEBUG as a release compiler flag

### ISSUE THREAD

**Issue by Sumith1896** [sympy/symengine#482]
The `NDEBUG` macro: http://en.cppreference.com/w/cpp/error/assert.
With this flag, the `assert`s will be skipped.
The macro itself is supposed to turn on/off assertions, but in general people use it to signal a release/debug switch. The library on which symengine depends might use this(example Piranha).
But the tests shouldn't be built then, they mostly use assert. So decision needed.

Reported by @bluescarni.
cc @certik @isuruf

**Comment by certik** [comment]
As discussed on gitter, we should move our testing framework to Catch (#282) and update SYMENGINE_ASSERT not to use assert. That way, SymEngine will not be affected by the NDEBUG macro. 

So we just need to turn off assertions for Piranha using NDEBUG, as it won't affect SymEngine.

**Comment by Sumith1896** [comment]
Closed via #498
