### ISSUE TITLE
Clang fails to build on linux in Release mode (on Travis)

### ISSUE THREAD

**Issue by certik** [sympy/symengine#486]
Then there is also some kind of a clang error (https://travis-ci.org/certik/symengine/jobs/68341285, https://travis-ci.org/certik/symengine/jobs/68341287):
```
[  1%] Building CXX object symengine/teuchos/CMakeFiles/teuchos.dir/Teuchos_dyn_cast.cpp.o

In file included from /home/travis/build/certik/symengine/symengine/teuchos/Teuchos_dyn_cast.cpp:42:

In file included from /home/travis/build/certik/symengine/symengine/teuchos/Teuchos_dyn_cast.hpp:46:

In file included from /home/travis/build/certik/symengine/symengine/teuchos/Teuchos_TypeNameTraits.hpp:50:

In file included from /home/travis/build/certik/symengine/symengine/teuchos/Teuchos_ConstTypeTraits.hpp:46:

In file included from /home/travis/build/certik/symengine/symengine/teuchos/Teuchos_ConfigDefs.hpp:86:

In file included from /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/cmath:46:

In file included from /usr/include/math.h:427:

/usr/include/x86_64-linux-gnu/bits/math-finite.h:177:1: error: unknown type name

      '__extern_always_inline'

__extern_always_inline double __NTH (lgamma (double __d))

^
```
Not sure what causes that. Here is the exact same error as well: https://groups.google.com/d/topic/travis-ci/iy4tXzwgtsE/discussion

**Comment by isuruf** [comment]
This is due to adding `-ffast-math` flag in Release mode. https://llvm.org/bugs/show_bug.cgi?id=13745

**Comment by certik** [comment]
I see, thanks! One solution is not to use `-ffast-math`, and it only influences machine floating point operations (e.g. a double), but it does speed it up. So I prefer the other solution (if it works), i.e. add `-D__extern_always_inline="extern __always_inline"` into the g++ command line flags.

**Comment by certik** [comment]
Actually the best solution is probably to use libc++ with clang, then things should work.
