### ISSUE TITLE
C Wrapper function for get_type_code in Basic

### ISSUE THREAD

**Issue by abinashmeher999** [sympy/symengine#517]
The function `Basic::get_type_code()` returns the enum `TypeID`, for the corresponding class. To wrap this function in C, the obvious approach would be to `#define` preprocessor flags that have the corresponding int associated to them. like:
```c
#define INTEGER 0
#define RATIONAL 1
//likewise
```
This is not robust to any changes that are done in the header file of the Basic. 
> ```cpp
// The 'TypeID_Count' returns the number of elements in 'TypeID'. For this
// to work, do not assign numbers to the elements above (or if you do, you
// must assign the correct count below).
```

This means there is a chance in the future that numbers might be assigned to these enums. We won't want that to break the system.
- One approach is to mention in the comment to also update the C header file, i.e. cwrapper.h. with the correct number for all the TypeIDs
- Other approach is this
```c
//cwrapper.h
#define INTEGER typecodes.integer
#define RATIONAL typecodes.rational
//likewise

typedef struct {
    int integer;
    int rational;
    //...
} TypeID;

static TypeID typecodes;
```
In the source file
```cpp
//cwrapper.cpp
extern "C" {
    typecodes.integer = SymEngine::INTEGER;
    typecodes.rational = SymEngine::RATIONAL;
    //...
}
```
How should we go about this? 
cc @certik @isuruf ?

**Comment by isuruf** [comment]
Why don't you move the definition of the enum types to a new header file `symengine_types.h` ? It can be included in both C headers and C++ headers.

**Comment by abinashmeher999** [comment]
Yes! That can be done too. But I read somewhere that enum in C came only after C99. So to make it compatible with all versions usually the `#define` method is adopted. I will search for the source where I read this.

**Comment by abinashmeher999** [comment]
Sorry, a small correction, **enums are supported after C89/ANSI C**.
http://cplus.about.com/od/introductiontoprogramming/p/enumeration.htm
Here in the first few lines it says that enum is not supported in K&R C(I think the only standard version before C89), and in that case `#define` should be used.

**Comment by certik** [comment]
I found some options here:
http://stackoverflow.com/questions/20792121/wrap-c-namespaced-enum-to-c-interface

But if we can just use enum, that would be the best.

**Comment by certik** [comment]
Let's use enum, seems like even the linux kernel is using it. So just
create type_codes.h and include it in both C++ and the C header file
properly.

**Comment by abinashmeher999** [comment]
Thanks! That should be convenient. I am doing it.

**Comment by isuruf** [comment]
Maybe we should prepend `SYMENGINE_` to all the type names to avoid name clashes.

**Comment by abinashmeher999** [comment]
My code has something like this
```cpp
#ifndef __cplusplus
typedef enum TypeID TYPEID;
#endif
```
I am trying to typedef TypeID to TYPEID when it is being included in a file to be compiled by c compiler, i.e. cwrapper.h. This doesn't seem to work. Am I missing something?

**Comment by abinashmeher999** [comment]
Even with this as the function signature as this
```cpp
//Returns the typeID of the basic struct
enum TypeID basic_get_type(const basic s);
```
I get the error
```
In file included from /home/abinashmeher999/gsoc/symengine/symengine/cwrapper.cpp:5:0:
/home/abinashmeher999/gsoc/symengine/symengine/cwrapper.h:79:6: error: use of enum ‘TypeID’ without previous declaration
 enum TypeID basic_get_type(const basic s);
      ^
```
I am pushing the code.

**Comment by certik** [comment]
One can use the approach in http://stackoverflow.com/a/20792525/479532 to have prefixed values in C.

**Comment by abinashmeher999** [comment]
So this one requires One more header like `type_codes.h`, and all other declarations can go to their respective header files, i.e. basic.h and cwrapper.h . Shall I try this once? Or try to debug the common header for both C and C++ approach?

**Comment by certik** [comment]
I would do the following, it should work:
```
/* type_codes.h */
FOO_ENUM(APPLE) = 0,
FOO_ENUM(ORANGE)
Then in the C header:

/* C interface */
typedef enum {
#   define FOO_ENUM(id) FOO_##id
#   include "Fruit.h"
#   undef FOO_ENUM
} Foo_Fruit_t;
And finally in the C++ header:

// C++ interface
namespace Foo {
    enum Fruit_t {
#       define FOO_ENUM(id) id
#       include "Fruit.h"
#       undef FOO_ENUM
    };
}
```
