### ISSUE TITLE
Using the new type_codes.inc file to simplify code in visitor.cpp

### ISSUE THREAD

**Issue by abinashmeher999** [sympy/symengine#520]
The code in [cwrapper.cpp](https://github.com/sympy/symengine/blob/d29cc084bb648d941955b0d746e8aa1a09f75252/symengine/visitor.cpp#L22) uses a macro on all the enumerated types in namespace SymEngine. After the inclusion of `type_codes.inc` file in #519, this can be simplified.

**Comment by isuruf** [comment]
+1
Also in `Visitor` class and `BaseVisitor` class

**Comment by abinashmeher999** [comment]
@isuruf How about we enlist all the Class names along with their TypeID in `type_codes.inc`. Like,
```
SYMENGINE_ENUM(FUNCTIONSYMBOL, FunctionSymbol),
SYMENGINE_ENUM(DIRICHLET_ETA, Dirichlet_eta),
//likewise
```
So, that we can choose what argument we want to use. For enum we can use the first argument and ignore the second and for cases in `Visitor` and `BaseVisitor`, we can ignore the first argument and use the second argument i.e. name.

**Comment by isuruf** [comment]
Sounds good

**Comment by certik** [comment]
+1

Also you should remove the trailing comma (`,`) from `type_codes.inc`, and only add it in in the enum, but not add it in the visitor.cpp.
