### ISSUE TITLE
Test SymEngine using gcc on OS X

### ISSUE THREAD

**Issue by certik** [sympy/symengine#563]
It looks like we are testing `gcc` on OS X at first sight, but it turns out that `gcc` is just a symlink to Apple clang on OS X.... See here: https://travis-ci.org/sympy/symengine/jobs/72114071 and the line:
```
$ export CXX=g++
$ export CC=gcc
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
```

So we are actually testing with clang twice. Either we should remove the "gcc" OS X tests, or (ideally) figure out how to actually test gcc on OS X.

**Comment by isuruf** [comment]
That's the default, but we are overriding the compiler wee are using here, https://github.com/sympy/symengine/blob/6e154afa9a9000984ded6ba0d851a6c72ffd9277/bin/install_travis.sh#L14.

CMake is showing the compiler as `GNU 4.8.3` which means we are testing with `gcc`.
https://travis-ci.org/sympy/symengine/jobs/72114071#L2921

**Comment by certik** [comment]
Ah, cool! I didn't realize that. So I think all is good. Sorry for the noise.
