### ISSUE TITLE
Non-conforming naming of Python extension module shared object (PEP 3149)

### ISSUE THREAD

**Issue by bjodah** [sympy/symengine#604]
I guess this is related to how CMake is configured to build the extension module.
On my Ubuntu 14.04 machine, running cmake with `-DPYTHON_BIN=python3.4m` and then building produces a shared object file named: `symengine_wrapper.so`.
I would however expect the file to be named: `symengine_wrapper.cpython-34m.so`.

Reference: [PEP 3149](https://www.python.org/dev/peps/pep-3149/)

**Comment by certik** [comment]
How is the new module imported? Still with `import symengine_wrapper`? There seem to be failures in #606 due to this.

**Comment by bjodah** [comment]
Yes, there is no visible changes to user's Python code.
If you run distutils provided with Py 3.4 for example it does this, python3.4 binary is then clever enough to look for the "PEP 3149 name" first, I wouldn't change the name for Py 2.x though since distutils isn't doing so.
