### ISSUE TITLE
Convert imaginary sympy expressions to symengine

### ISSUE THREAD

**Issue by bjodah** [sympy/symengine#611]
Consider this:
```
In [19]: a = sympy.S(3.14j)

In [20]: type(a)
Out[20]: sympy.core.mul.Mul

In [21]: a.args
Out[21]: (3.14000000000000, I)

In [22]: type(a.args[0]), type(a.args[1])
Out[22]: (sympy.core.numbers.Float, sympy.core.numbers.ImaginaryUnit)
```

I find no dispatch for `ImaginaryUnit` in `sympy2symengine`. Have I overlooked something?

**Comment by bjodah** [comment]
See this commit:
https://github.com/bjodah/symengine/commit/75d178e494e4a088602845f29d0d84c2b577f443

We could add a kwarg `prefer_mpc=True` in analogy?

**Comment by isuruf** [comment]
It should be of type `Complex` which is an exact type for complex numbers of the form `a+b*I` where `a` and `b` are `Rational` types

**Comment by isuruf** [comment]
It is already here, https://github.com/sympy/symengine/blob/8537c67507fae9b1d8d575d322c6ade4f1a59297/symengine/python/symengine/lib/symengine_wrapper.pyx#L124

**Comment by bjodah** [comment]
Oh, I see, sorry for the false positive.
